### ISSUE TITLE
请问这个插件没有维持更新了吗？

### ISSUE THREAD

**Issue by fcw528** [HsuanXyz/ng-zorro-live-templates#2]
请问这个插件没有维持更新了吗？我看ng.ant.design增加了一些新的组件都没有live-templates

**Comment by hsuanxyz** [comment]
@fcw528 重新整理了下组件，节前会提交更新，之后等 IntelliJ 审核。

**Comment by fcw528** [comment]
收到，辛苦了，感谢分享，祝国庆快乐：）
